serve_addr: ":8181"
timeout: "30s"
script_manager: "manager"

database:
  kind: postgres
  host: localhost
  port: 5432
  user: postgres
  pass: ""
  dbname: postgres
  max_connections: 10
  timeout: 10

