serve_addr: ":8181"
timeout: "30s"
script_manager: "manager"

database:
  kind: postgres
  host: localhost
  port: 5433
  user: erius
  pass: "4L7Npbjee4s2XvTe"
  dbname: pipeliner
  max_connections: 10
  timeout: 10

