include:
  - project: 'abp/ci-templates'
    ref: v5
    file: '/entrypoints/app/go_base_auto_push.yml'


variables:
  # KUBERNETES_MEMORY_LIMIT: 1Gi
  # KUBERNETES_CPU_LIMIT: 500m
  K8S_WORKLOAD_TYPE: statefulset
  WRK_MEMORY_LIMIT_KUSTOMIZE: 521Mi
  WRK_CPU_LIMIT_KUSTOMIZE: 1
  ENABLED_DEPLOY: "true"
#  ENABLED_LINT: 'allow-failure-true'
  ENABLED_REVIEW: 'allow-failure-true'
  ENABLED_DEP_CHECK: 'allow-failure-true'
  # ENABLED_TEST: 'allow-failure-true'
  CONFIG_PATH: cmd/pipeliner/config.yaml
  WRK_MEMORY_LIMIT_LINT: 6Gi
  WRK_CPU_LIMIT_LINT: 2
  WRK_MEMORY_LIMIT_REVIEW: 2Gi
  WRK_LIMIT_CPU_REVIEW: 2
  GOLANGCI_LINT_TIMEOUT: 30m
  WRK_MEMORY_LIMIT_DEPLOY_HELPER:   1024Mi
  WRK_MEMORY_LIMIT_DEPLOY:          1024Mi
  WRK_IMG_GOLANG_BUILD: registry.services.mts.ru/docker/golang/all:1.20.0-alpine3.17.1-gcc-v1
  ROLLOUT_TIMEOUT: 1200s

deploy staging:
  variables:
    K8S_WORKLOAD_TYPE: deployment

deploy production:
  variables:
    K8S_WORKLOAD_TYPE: deployment
