include:
  - project: 'abp/ci-templates'
    ref: v5
    file: '/entrypoints/app/go_base_auto_push.yml'


variables:
  ENABLED_DEPLOY: "false"
  ENABLED_LINT: 'allow-failure-true'
  ENABLED_REVIEW: 'allow-failure-true'
  ENABLED_DEP_CHECK: 'allow-failure-true'
  ENABLED_TEST: 'allow-failure-true'
  CONFIG_PATH: example/config/config.yaml
