linters-settings:
  govet:
    check-shadowing: true
    fieldalignment: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  # gci:
  #   sections:
  #   # все дефолтные 
  #     - standard
  #   # _ "github.com/lib/lib"
  #     - blank
  #   # third party
  #     - default
  #   # все от мтс
  #     - prefix(gitlab.services.mts.ru)
  #   # специально для functions runner
  #     - prefix(gitlab.services.mts.ru/functions-runner)
  #   # jocasta
  #     - prefix(gitlab.services.mts.ru/jocasta)
  #   custom-order: true
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
  depguard:
    rules:
      main:
        files: 
          - $all
        deny:
          - pkg: "github.com/labstack/gommon/log"
            description: используем только gitlab.services.mts.ru/abp/myosotis/logger  

linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - prealloc
    - revive
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
    - depguard
    # - gci

severity:
  default-severity: error

run:
  tests: false
  skip-dirs:
    - swagger-ui
    - configs
    - templates
    - \.go
    - migrations
  skip-files:
    - .*-local.*
