serve_addr: ":8181"
timeout: "30s"
script_manager: "manager"
faas: "https://openfaas.dev.autobp.mts.ru/"


database:
  kind: postgres
  host: localhost
  port: 5433
  user: erius
  pass: "4L7Npbjee4s2XvTe"
  dbname: postgres
  max_connections: 10
  timeout: 10

swagger:
  base_path: "/api/pipeliner/v1"
  version: "0.1"
  host: "localhost"
  port: "1234"