version: "3.1"
networks:
  mynet:
services:
  pg:
    image: postgres:latest
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-postgres}"
      POSTGRES_USER: "${POSTGRES_USER:-user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-1234}"
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    networks:
      - mynet
  app:
    # build: #./path to dockerfile
    #  dockerfile: ./app.dockerfile
    image: school_app
    depends_on:
      - pg
    environment:
      POSTGRES_HOST: pg
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_DB: "${POSTGRES_DB:-postgres}"
      POSTGRES_USER: "${POSTGRES_USER:-user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-1234}"
    networks:
      - mynet
    ports:
      - 8080:8080
    restart: always
