// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/pipeliner/v1/metrics": {
            "get": {
                "description": "Метрики",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "metrics",
                "operationId": "metrics",
                "responses": {
                    "200": {
                        "description": "metrics content"
                    }
                }
            }
        },
        "/debug/": {
            "post": {
                "description": "Создать сессию отладки",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "debug"
                ],
                "summary": "Create debug task",
                "operationId": "create-debug-task",
                "parameters": [
                    {
                        "description": "New debug task",
                        "name": "debug",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusTask"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/debug/run": {
            "post": {
                "description": "Начать отладку",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "debug"
                ],
                "summary": "Start debug task",
                "operationId": "debug-task-run",
                "parameters": [
                    {
                        "description": "debug request",
                        "name": "variables",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.DebugRunRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusTask"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/debug/{taskID}": {
            "get": {
                "description": "Получить debug-задачу",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Debug task",
                "operationId": "debug-task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "work number",
                        "name": "workNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.DebugResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/modules": {
            "get": {
                "description": "Список блоков",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modules"
                ],
                "summary": "Get list of modules",
                "operationId": "get-modules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusFunctionList"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/modules/usage": {
            "get": {
                "description": "Блоки и сценарии, в которых они используются",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modules"
                ],
                "summary": "Get list of modules usage",
                "operationId": "modules-usage",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.AllUsageResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/modules/{moduleName}": {
            "post": {
                "description": "Запустить блок",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modules"
                ],
                "summary": "Run Module By Name",
                "operationId": "module-usage-by-name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "module name",
                        "name": "moduleName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.UsageResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/modules/{moduleName}/usage": {
            "get": {
                "description": "Сценарии, в которых используется блок",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modules"
                ],
                "summary": "Usage of module in pipelines",
                "operationId": "module-usage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "module name",
                        "name": "moduleName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.UsageResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/pipelines": {
            "get": {
                "description": "Список сценариев",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipeline"
                ],
                "summary": "Get list of pipelines",
                "operationId": "list-pipelines",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusScenarioList"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            },
            "post": {
                "description": "Создать новый сценарий",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipeline"
                ],
                "summary": "Create pipeline",
                "operationId": "create-pipeline",
                "parameters": [
                    {
                        "description": "New scenario",
                        "name": "pipeline",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.EriusScenario"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusScenario"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/pipelines/version": {
            "put": {
                "description": "Изменить черновик",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipeline"
                ],
                "summary": "Edit Draft",
                "operationId": "edit-draft",
                "parameters": [
                    {
                        "description": "New draft",
                        "name": "draft",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.EriusScenario"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusScenario"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/pipelines/version/{pipelineID}": {
            "post": {
                "description": "Создать новую версию сценария",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "Create pipeline version",
                "operationId": "create-version",
                "parameters": [
                    {
                        "description": "New version",
                        "name": "pipeline",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.EriusScenario"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "pipelineID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusScenario"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/pipelines/version/{versionID}": {
            "get": {
                "description": "Получить версию сценария по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "Get pipeline version",
                "operationId": "get-version",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Version ID",
                        "name": "versionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusScenario"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удалить версию",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "Delete Version",
                "operationId": "delete-version",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Version ID",
                        "name": "versionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/pipelines/{pipelineID}": {
            "get": {
                "description": "Получить сценарий по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipeline"
                ],
                "summary": "Get pipeline",
                "operationId": "get-pipeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "pipelineID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusScenario"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удалить сценарий",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipeline"
                ],
                "summary": "Delete Pipeline",
                "operationId": "delete-pipeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "pipelineID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/pipelines/{pipelineID}/scheduler-tasks": {
            "post": {
                "description": "Наличие у сценария активных заданий в шедулере",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipeline"
                ],
                "summary": "Active scheduler tasks",
                "operationId": "pipeline-scheduler-tasks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "pipelineID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.SchedulerTasksResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/pipelines/{pipelineID}/tags": {
            "get": {
                "description": "Список тегов сценария",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipeline",
                    "tags"
                ],
                "summary": "Get Pipeline Tags",
                "operationId": "get-pipeline-tags",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "pipelineID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.EriusTagInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/pipelines/{pipelineID}/tags/{ID}": {
            "put": {
                "description": "Прикрепить тег к сценарию",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipeline",
                    "tags"
                ],
                "summary": "Attach Tag",
                "operationId": "attach-tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "pipelineID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tag ID",
                        "name": "ID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusTagInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Открепить тег от сценария",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipeline",
                    "tags"
                ],
                "summary": "Detach Tag",
                "operationId": "detach-tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "pipelineID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tag ID",
                        "name": "ID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/run/version/{versionID}": {
            "post": {
                "description": "Запустить версию",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version",
                    "run"
                ],
                "summary": "Run Version",
                "operationId": "run-version",
                "parameters": [
                    {
                        "description": "pipeline input",
                        "name": "variables",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RunVersionBody"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Version ID",
                        "name": "versionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.RunResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/run/versions/blueprint_id": {
            "post": {
                "description": "Запустить все версии c blueprintID и первым блоком sd_application",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version",
                    "run"
                ],
                "summary": "Run Version By blueprintID",
                "operationId": "run-versions-by-blueprint-id",
                "parameters": [
                    {
                        "description": "pipeline input",
                        "name": "variables",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RunVersionsByBlueprintIdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.RunVersionsByBlueprintIdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/run/{pipelineID}": {
            "post": {
                "description": "Запустить сценарий",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipeline",
                    "run"
                ],
                "summary": "Run Pipeline",
                "operationId": "run-pipeline",
                "parameters": [
                    {
                        "description": "pipeline input",
                        "name": "variables",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RunPipelineBody"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "pipelineID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.RunResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/tags": {
            "get": {
                "description": "Cписок тегов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Get Tags",
                "operationId": "get-tags",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.EriusTagInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            },
            "put": {
                "description": "Изменить тег",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Edit Tag",
                "operationId": "edit-tag",
                "parameters": [
                    {
                        "description": "Modified tag",
                        "name": "tag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.EriusTagInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusTagInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            },
            "post": {
                "description": "Создать новый тег",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Create Tag",
                "operationId": "create-tag",
                "parameters": [
                    {
                        "description": "New tag",
                        "name": "tag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.EriusTagInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusTagInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/tags/{ID}": {
            "delete": {
                "description": "Удалить тег",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Remove Tag",
                "operationId": "remove-tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag ID",
                        "name": "ID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "description": "Получить задачи",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipeline",
                    "tasks"
                ],
                "summary": "Get Tasks",
                "operationId": "get-tasks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "Task IDs",
                        "name": "taskIDs",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Created after",
                        "name": "created[start]",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Created before",
                        "name": "created[end]",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusTasksPage"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/tasks/last-by-version/{versionID}": {
            "get": {
                "description": "Получить последнюю debug-задачу версии сценария",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Get last debug task for version",
                "operationId": "get-version-last-debug-task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Version ID",
                        "name": "versionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusTask"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/tasks/pipeline/{pipelineID}": {
            "get": {
                "description": "Получить задачи по сценарию",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipeline",
                    "tasks"
                ],
                "summary": "Get Pipeline Tasks",
                "operationId": "get-pipeline-tasks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "pipelineID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusTasks"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/tasks/version/{versionID}": {
            "get": {
                "description": "Получить задачи по версии сценарию",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version",
                    "tasks"
                ],
                "summary": "Get Version Tasks",
                "operationId": "get-version-tasks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Version ID",
                        "name": "versionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.EriusTasks"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        },
        "/tasks/{taskID}": {
            "get": {
                "description": "Получить экземпляр задачи",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Get Task",
                "operationId": "get-task-entity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "work number",
                        "name": "workNumber",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.httpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.eriusTaskResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            },
            "post": {
                "description": "Update task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Update Task",
                "operationId": "update-task-entity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "work number",
                        "name": "workNumber",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Task update data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.TaskUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.httpError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.AllUsageResponse": {
            "type": "object",
            "properties": {
                "pipelines": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "entity.DebugResult": {
            "type": "object",
            "properties": {
                "block_name": {
                    "type": "string"
                },
                "break_points": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "description": "todo define values",
                    "type": "string",
                    "example": "run,error,finished,created"
                },
                "task": {
                    "$ref": "#/definitions/entity.EriusTask"
                }
            }
        },
        "entity.EriusFunc": {
            "type": "object",
            "properties": {
                "block_type": {
                    "type": "string",
                    "enum": [
                        "python3",
                        "go",
                        "internal",
                        "term",
                        "scenario"
                    ],
                    "example": "python3"
                },
                "final": {
                    "type": "string"
                },
                "input": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.EriusFunctionValue"
                    }
                },
                "next": {
                    "type": "string",
                    "example": "send-data_0"
                },
                "on_false": {
                    "type": "string"
                },
                "on_iter": {
                    "type": "string"
                },
                "on_true": {
                    "type": "string"
                },
                "output": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.EriusFunctionValue"
                    }
                },
                "param_type": {
                    "type": "string"
                },
                "params": {
                    "type": "object"
                },
                "title": {
                    "type": "string",
                    "example": "lock-bts"
                },
                "type_id": {
                    "type": "string",
                    "example": "approver"
                },
                "x": {
                    "type": "integer"
                },
                "y": {
                    "type": "integer"
                }
            }
        },
        "entity.EriusFunctionList": {
            "type": "object",
            "properties": {
                "funcs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/script.FunctionModel"
                    }
                },
                "shapes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/script.ShapeEntity"
                    }
                }
            }
        },
        "entity.EriusFunctionValue": {
            "type": "object",
            "properties": {
                "global": {
                    "type": "string",
                    "example": "block.some_data"
                },
                "name": {
                    "type": "string",
                    "example": "some_data"
                },
                "type": {
                    "type": "string",
                    "example": "string"
                }
            }
        },
        "entity.EriusScenario": {
            "type": "object",
            "properties": {
                "approved_at": {
                    "type": "string",
                    "example": "2020-07-16T17:10:25.112704+03:00"
                },
                "author": {
                    "type": "string",
                    "example": "testAuthor"
                },
                "comment": {
                    "type": "string"
                },
                "comment_rejected": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string",
                    "example": "2020-07-16T17:10:25.112704+03:00"
                },
                "hasDraft": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "916ad995-8d13-49fb-82ee-edd4f97649e2"
                },
                "input": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.EriusFunctionValue"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "ScenarioName"
                },
                "output": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.EriusFunctionValue"
                    }
                },
                "pipeline": {
                    "type": "object",
                    "properties": {
                        "blocks": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/entity.EriusFunc"
                            }
                        },
                        "entrypoint": {
                            "type": "string"
                        }
                    }
                },
                "status": {
                    "description": "1 - Draft, 2 - Approved, 3 - Deleted, 4 - Rejected, 5 - On Approve",
                    "type": "integer",
                    "enum": [
                        1,
                        2,
                        3,
                        4,
                        5
                    ]
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.EriusTagInfo"
                    }
                },
                "version_id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "916ad995-8d13-49fb-82ee-edd4f97649e2"
                }
            }
        },
        "entity.EriusScenarioInfo": {
            "type": "object",
            "properties": {
                "approved_at": {
                    "type": "string",
                    "example": "2020-07-16T17:10:25.112704+03:00"
                },
                "approver": {
                    "type": "string",
                    "example": "testApprover"
                },
                "author": {
                    "type": "string",
                    "example": "testAuthor"
                },
                "comment": {
                    "type": "string"
                },
                "comment_rejected": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string",
                    "example": "2020-07-16T17:10:25.112704+03:00"
                },
                "id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "916ad995-8d13-49fb-82ee-edd4f97649e2"
                },
                "last_run": {
                    "type": "string",
                    "example": "2020-07-16T17:10:25.112704+03:00"
                },
                "last_run_status": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "ScenarioName"
                },
                "status": {
                    "description": "1 - Draft, 2 - Approved, 3 - Deleted, 4 - Rejected, 5 - On Approve",
                    "type": "integer",
                    "enum": [
                        1,
                        2,
                        3,
                        4,
                        5
                    ]
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.EriusTagInfo"
                    }
                },
                "version_history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.EriusVersionInfo"
                    }
                },
                "version_id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "916ad995-8d13-49fb-82ee-edd4f97649e2"
                }
            }
        },
        "entity.EriusScenarioList": {
            "type": "object",
            "properties": {
                "drafts": {
                    "description": "Черновики",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.EriusScenarioInfo"
                    }
                },
                "on_approve": {
                    "description": "Сценарии на одобрении",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.EriusScenarioInfo"
                    }
                },
                "pipelines": {
                    "description": "Согласованные сценарии",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.EriusScenarioInfo"
                    }
                },
                "tags": {
                    "description": "Теги",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.EriusTagInfo"
                    }
                }
            }
        },
        "entity.EriusTagInfo": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "916ad995-8d13-49fb-82ee-edd4f97649e2"
                },
                "isMarker": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "description": "1 - Created, 3 - Deleted",
                    "type": "integer",
                    "enum": [
                        1,
                        3
                    ]
                }
            }
        },
        "entity.EriusTask": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "debug": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "last_changed_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Step"
                    }
                },
                "version_id": {
                    "type": "string"
                },
                "work_number": {
                    "type": "string"
                }
            }
        },
        "entity.EriusTasks": {
            "type": "object",
            "properties": {
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.EriusTask"
                    }
                }
            }
        },
        "entity.EriusTasksPage": {
            "type": "object",
            "properties": {
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.EriusTask"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "entity.EriusVersionInfo": {
            "type": "object",
            "properties": {
                "approved_at": {
                    "type": "string",
                    "example": "2020-07-16T17:10:25.112704+03:00"
                },
                "approver": {
                    "type": "string",
                    "example": "testApprover"
                },
                "author": {
                    "type": "string",
                    "example": "testAuthor"
                },
                "created_at": {
                    "type": "string",
                    "example": "2020-07-16T17:10:25.112704+03:00"
                },
                "version_id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "916ad995-8d13-49fb-82ee-edd4f97649e2"
                }
            }
        },
        "entity.RunResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "output": {},
                "pipeline_id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "916ad995-8d13-49fb-82ee-edd4f97649e2"
                },
                "status": {
                    "type": "string",
                    "example": "runned"
                },
                "work_number": {
                    "type": "string"
                }
            }
        },
        "entity.SchedulerTasksResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "boolean"
                }
            }
        },
        "entity.Step": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "has_error": {
                    "type": "boolean"
                },
                "is_finished": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "state": {
                    "type": "object"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "storage": {
                    "type": "object",
                    "additionalProperties": true
                },
                "time": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "entity.TaskUpdate": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "approvement"
                    ],
                    "example": "approvement"
                },
                "parameters": {
                    "type": "object"
                }
            }
        },
        "entity.UsageResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Имя блока",
                    "type": "string"
                },
                "pipelines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.UsedBy"
                    }
                },
                "used": {
                    "type": "boolean"
                }
            }
        },
        "entity.UsedBy": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID сценария",
                    "type": "string"
                },
                "name": {
                    "description": "Имя сценария",
                    "type": "string"
                }
            }
        },
        "handlers.CreateTaskRequest": {
            "type": "object",
            "properties": {
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                },
                "version_id": {
                    "type": "string"
                }
            }
        },
        "handlers.DebugRunRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "example": "step_over,resume"
                },
                "break_points": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "work_number": {
                    "type": "string"
                }
            }
        },
        "handlers.RunPipelineBody": {
            "type": "object",
            "additionalProperties": true
        },
        "handlers.RunVersionBody": {
            "type": "object",
            "additionalProperties": true
        },
        "handlers.RunVersionsByBlueprintIdRequest": {
            "type": "object",
            "properties": {
                "application_body": {
                    "type": "object",
                    "additionalProperties": true
                },
                "blueprint_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "handlers.RunVersionsByBlueprintIdResponse": {
            "type": "object",
            "properties": {
                "versions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.RunResponse"
                    }
                }
            }
        },
        "handlers.eriusTaskResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "debug": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "last_changed_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.step"
                    }
                },
                "version_id": {
                    "type": "string"
                },
                "work_number": {
                    "type": "string"
                }
            }
        },
        "handlers.httpError": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "handlers.httpResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "handlers.step": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "has_error": {
                    "type": "boolean"
                },
                "is_finished": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "state": {
                    "type": "object"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "storage": {
                    "type": "object",
                    "additionalProperties": true
                },
                "time": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "script.FunctionModel": {
            "type": "object",
            "properties": {
                "block_type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/script.FunctionValueModel"
                    }
                },
                "next_funcs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "outputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/script.FunctionValueModel"
                    }
                },
                "params": {
                    "$ref": "#/definitions/script.FunctionParams"
                },
                "shape_type": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "script.FunctionParams": {
            "type": "object",
            "properties": {
                "params": {},
                "type": {
                    "type": "string",
                    "enum": [
                        "approver",
                        "servicedesk_application"
                    ],
                    "example": "approver"
                }
            }
        },
        "script.FunctionValueModel": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "script.ShapeEntity": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1",
	Host:        "localhost:8181",
	BasePath:    "/api/pipeliner/v1",
	Schemes:     []string{},
	Title:       "Pipeliner API",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
